shared:
  image: node:8

parameters:
  p1: p1
  p2:
    value: p2
    description: User running build
  p3:
    value: p3
    description: this is a value for p3
  p4: p4
  p5: p5
  p6:
    value: [p6a, p6b]
    description: this is a value for p6

jobs:
  component:
    environment:
      JUMP_HOST: jump-host-hello
      API_REPLICAS: 2
    parameters:
      job_param_color:
        value: red
      job_param_car:
        value: [Audi, BMW, Tesla]
        description: car you own
    steps:
      - p1: echo $(meta get parameters.p1)
      - p2: echo $(meta get parameters.p2)
      - p3: echo $(meta get parameters.p3)
      - p4: echo $(meta get parameters.p4)
      - p5: echo $(meta get parameters.p5)
      - p6: echo $(meta get parameters.p6)
      - job_param_color: echo $(meta get parameters.job_param_color)
      - job_param_car: echo $(meta get parameters.job_param_car)

  publish:
    requires: component
    image: node:12
    environment:
      JUMP_HOST: jump-host-world
      API_REPLICAS: 5
    parameters:
      job_param_color: white
      job_param_music:
        value: [ Jazz, Rock, Country ]
        description: favorite music genre
    steps:
      - p1: echo $(meta get parameters.p1)
      - p2: echo $(meta get parameters.p2)
      - p3: echo $(meta get parameters.p3)
      - p4: echo $(meta get parameters.p4)
      - p5: echo $(meta get parameters.p5)
      - p6: echo $(meta get parameters.p6)
      - job_param_color: echo $(meta get parameters.job_param_color)
      - job_param_music: echo $(meta get parameters.job_param_music)
