shared:
    image: node:22
    parameters:
        fruit: [ "parent-apple", "child-apple", "shared-apple" ]
    annotations:
        screwdriver.cd/blockedBySameJobWaitTime: 15
    settings:
        email: [ parent.template@email.com, child.template@email.com, shared.config@email.com ]
        slack: 'sharedJobChannel'
    environment:
        ORIGIN: sharedConfig
        SHARED_JOB_ENV: "shared job env"
    steps:
        - hello: |
              echo 'hello'
        - world: |
              echo 'world'

jobs:
    job-using-parent-template-without-override:
        template: sagar1312/sd-job-template-parent@latest
        requires: [ ~commit ]
    job-using-child-template-without-override:
        template: sagar1312/sd-job-template-child@latest
        requires: [ job-using-parent-template-without-override ]

    job-using-parent-template-with-override:
        template: sagar1312/sd-job-template-parent@latest
        requires: [ ~commit ]
        image: node:23
        annotations:
            screwdriver.cd/blockedBySameJobWaitTime: 20
            screwdriver.cd/mergeSharedSteps: true
        settings:
            email: [ parent.template@email.com, child.template@email.com, shared.config@email.com, job.config@email.com ]
            slack: 'jobChannel'
        environment:
            ORIGIN: jobConfig
            JOB_ENV: "job env"
        order: [print_template_parameters, hello, world]
    job-using-child-template-with-override:
        template: sagar1312/sd-job-template-child@latest
        requires: [ job-using-parent-template-with-override ]
        image: node:23
        annotations:
            screwdriver.cd/blockedBySameJobWaitTime: 20
            screwdriver.cd/mergeSharedSteps: true
        settings:
            email: [ parent.template@email.com, child.template@email.com, shared.config@email.com, job.config@email.com ]
            slack: 'jobChannel'
        environment:
            ORIGIN: jobConfig
            JOB_ENV: "job env"
        order: [ print_template_parameters, more_step_in_child_template, hello, world ]

    job-not-using-template-without-override:
        requires: [ ~commit ]


    job-not-using-template-with-override:
        requires: [ ~commit ]
        annotations:
            screwdriver.cd/blockedBySameJobWaitTime: 20
        settings:
            email: [ job.config@email.com ]
            slack: 'jobChannel'
        environment:
            ORIGIN: jobConfig
            JOB_ENV: "job env"
        image: node:23
        steps:
            - fav-color: |
                  echo 'red'
