shared:
  image: node:8

jobs:
  component:
    requires: [~pr, ~commit]
    environment:
      JUMP_HOST: jump-host-hello
      API_REPLICAS: 2
    steps:
      - param_superuser: echo param_superuser = $(meta get parameters.param_superuser)
      - param_region: echo param_region = $(meta get parameters.param_region)
      - param_sports: echo param_sports = $(meta get parameters.param_sports)
      - param_color: echo param_color = $(meta get parameters.param_color)
      - param_car: echo param_car = $(meta get parameters.param_car)

  publish:
    requires: component
    image: node:12
    environment:
      JUMP_HOST: jump-host-world
      API_REPLICAS: 5
    steps:
      - param_superuser: echo param_superuser = $(meta get parameters.param_superuser)
      - param_region: echo param_region = $(meta get parameters.param_region)
      - param_sports: echo param_sports = $(meta get parameters.param_sports)
      - param_color: echo param_color = $(meta get parameters.param_color)
      - param_car: echo param_car = $(meta get parameters.param_car)