---
version: 4
shared:
    image: node:20
    annotations:
        screwdriver.cd/cpu: LOW
        screwdriver.cd/ram: LOW
jobs:
    main:
        requires:
            - ~commit
            - ~sd@13557:remote-upstream-trigger
        steps:
            - meta-before-set: |
                  set -x
                  meta get img_version
            - set-meta: |
                  set -x
                  if [[ "$(meta get img_version)" -eq "null" ]]; then
                      echo 'setting meta to v3.0.0'
                      meta set img_version "v3.0.0"
                      meta set label "v3.0.0"
                  else
                      echo 'skip setting meta'
                      echo 'meta is already set $(meta get img_version)'
                  fi
            - get-meta: |
                  set -x
                  meta get img_version
    publish:
        requires:
            - main
        steps:
            -   push-to-artifactory: |
                    set -x
                    echo 'published $(meta get img_version)'
            -   add-more-to-meta: |
                    set -x
                    meta set artifact_version "artifact-$(meta get img_version)"