---
version: 4
shared:
    image: node:20
    annotations:
        screwdriver.cd/cpu: LOW
        screwdriver.cd/ram: LOW

parameters:
    CUSTOM_VERSION: "v.0.0.0"

jobs:
    main:
        requires:
            - ~commit
            - ~sd@23028:remote-upstream-trigger
        steps:
            - meta-before-set: |
                  set -x
                  meta get img_version
            - set-meta: |
                  set -x
                  if [ "$(meta get img_version)" = "null" ]; then
                      echo "setting meta to $(meta get parameters.CUSTOM_VERSION.value)"
                      meta set img_version "$(meta get parameters.CUSTOM_VERSION.value)"
                      meta set label "$(meta get parameters.CUSTOM_VERSION.value)"
                  else
                      echo 'skip setting meta'
                      echo 'meta is already set $(meta get img_version)'
                  fi
            - get-meta: |
                  set -x
                  meta get img_version
    publish:
        requires:
            - main
        steps:
            -   push-to-artifactory: |
                    set -x
                    echo 'published $(meta get img_version)'
            -   add-more-to-meta: |
                    set -x
                    meta set artifact_version "artifact-$(meta get img_version)"
    publish-docker:
        requires:
            - publish
        steps:
            -   push-to-docker: |
                    set -x
                    echo 'published $(meta get img_version)'
            -   add-more-to-meta: |
                    set -x
                    meta set docker_version "docker-$(meta get img_version)"