## Stages by grouping
shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  # triggering-stage:
  #   requires: [~pr, ~commit]
  #   sourcePaths: ["boom/"]
  ci-deploy:
    requires: []
  ci-test:
    requires: [ci-deploy]
  ci-certify:
    requires: [ci-test]
  # triggered-by-stage:
  #   requires: [~stage@integration]

stages:
  integration:
    requires: [~commit]
    jobs: [ci-deploy, ci-test, ci-certify]
    description: "This stage will deploy the latest application to the CI environment and certify it after the tests have passed."
    setup:
      image: node:lts
      steps:
        - init: echo 'integration setup'
      sourcePaths: ["boom/"]
#  ci:
#    requires: [ triggering-stage ]
#    jobs: [ ci-deploy, ci-test, ci-certify ]
#    description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."
