shared:
  image: node:12

parameters:
  DOWNSTREAM_PARAM_MUSIC: Rock
  DOWNSTREAM_PARAM_MOVIE: Sci-Fi

jobs:
  triggered_by_upstream:
    requires: [ ~pr, ~sd@6:triggers_downstream ]
    steps:
      - step_print_template_parameters: |
          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)

  filler:
    requires: [ triggered_by_upstream ]
    steps:
      - step_print_template_parameters: |
          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)

  triggers_upstream:
    requires: [ filler ]
    steps:
      - step_print_template_parameters: |
          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)
