## Stages by grouping
shared:
    image: node:20
    steps:
        - init: echo 'init'
jobs:
    triggering-stage:
        requires: [~pr, ~commit]
    overlapping-non-stage-job-at-start-1:
        requires: [triggering-stage]
    overlapping-non-stage-job-at-start-2a:
        requires: [ overlapping-non-stage-job-at-start-1 ]
    overlapping-non-stage-job-at-start-2b:
        requires: [ overlapping-non-stage-job-at-start-1 ]
    ci-deploy:
        requires: [ ~stage@integration ]
    ci-test-batch-1:
        requires: [ ci-deploy ]
    ci-test-batch-2:
        requires: [ ci-deploy ]
    ci-certify:
        requires: [ ci-test-batch-1, ci-test-batch-2 ]
    overlapping-non-stage-job-at-end-1:
        requires: [ ci-test-batch-1 ]
    overlapping-non-stage-job-at-end-2:
        requires: [ ci-test-batch-2 ]
    triggered-by-stage:
        requires: [ ~stage@integration ]

stages:
    integration:
        requires: [triggering-stage]
        jobs: [ci-deploy, ci-test-batch-1, ci-test-batch-2, ci-certify]
        description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."