## Stages by grouping
shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  component:
    requires: [~pr, ~commit]
  publish:
    requires: [ component ]
  ci-deploy:
    requires: []
  ci-test:
    requires: [ ci-deploy ]
  ci-certify:
    requires: [ ci-test ]
  prod-blue-deploy:
    requires: []
  prod-blue-test:
    requires: [ prod-blue-deploy ]
    steps:
      - fail: exit 1;
  prod-blue-certify:
    requires: [ prod-blue-test ]


stages:
  integration:
    requires: [ publish ]
    jobs: [ci-deploy, ci-test, ci-certify]
    description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."
  production-blue:
    requires: [stage@integration]
    jobs: [ prod-blue-deploy, prod-blue-test, prod-blue-certify ]
    description: "This stage will deploy the CI certified application to production BLUE environment and certifies it after the tests are passed."
    teardown:
      image: node:lts
      steps:
        - init: echo 'production-blue teardown'