## Stages by grouping
shared:
    image: node:14
    steps:
        - init: echo 'init'
jobs:
    component:
        requires: [~pr, ~commit]
    publish:
        requires: [ component ]
    deploy-a:
        requires: [ publish ]
    deploy-b:
        requires: [ publish ]