shared:
  image: node:14
  steps:
    - init: echo 'init'

jobs:
  triggering-ci:
    requires: [ ~pr, ~commit ]
  ci-setup-virtual:
    requires: [ ~triggering-ci ]
    annotations:
      screwdriver.cd/virtualJob: true
  ci-deploy:
    requires: [ ~ci-setup-virtual ]
    steps:
      - newdir: |
          mkdir -p $SD_ARTIFACTS_DIR/.boom
          echo "boom boom" > $SD_ARTIFACTS_DIR/.boom/boomfile
