shared:
  image: node:12

parameters:
  DOWNSTREAM_PARAM_MUSIC: Rock
  DOWNSTREAM_PARAM_MOVIE: Sci-Fi

jobs:
  set-meta:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          export REASON = "hello world"
          meta set cmr_reason ${REASON}
  set-meta-fail:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          meta set cmr_reason ${REASON}
  set-meta-v3:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          export REASON = "hello world"
          meta set cmr_reason $REASON