shared:
  image: node:12

parameters:
  DOWNSTREAM_PARAM_MUSIC: Rock
  DOWNSTREAM_PARAM_MOVIE: Sci-Fi

jobs:
  set-meta-v1:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          export REASON="hello world"
          meta set cmr_reason ${REASON}
  set-meta-v2:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          meta set cmr_reason ${REASON}
  set-meta-v3:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          export REASON="hello world"
          meta set cmr_reason $REASON
  set-meta-v4:
    requires: [ ~commit ]
    steps:
      - step_print_template_parameters: |
          export REASON="hello world"
          echo $REASON
          echo ${REASON}
          meta set HELLO "$REASON"