## Stages by grouping
shared:
    image: node:14
    steps:
        - init: echo 'init'
jobs:
    component:
        requires: [~pr, ~commit]
    publish:
        requires: [ ~component, ~sd@15151:publish ]
        steps:
          - warning: meta set build.warning true
    deploy:
        requires: [ sd@15151:deploy-a, sd@15152:deploy-b ]
