shared:
  image: node:12

parameters:
  DOWNSTREAM_PARAM_MUSIC: Rock
  DOWNSTREAM_PARAM_MOVIE: Sci-Fi

jobs:
  triggered_by_upstream:
    requires: [ ~pr, ~sd@6:triggers_downstream ]
    steps:
      - step_print_template_parameters: |
          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)
      - step_update_meta: |
          echo UPSTREAM_PARAM_COLOR = $(meta get parameters.UPSTREAM_PARAM_COLOR --external sd@6:triggers_downstream)
          meta set RELEASE_TYPE "stable"
          meta set YEAR "2022"

#  filler:
#    requires: [ triggered_by_upstream ]
#    steps:
#      - step_print_template_parameters: |
#          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
#          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)

  triggers_upstream:
    requires: [ triggered_by_upstream ]
    steps:
      - step_print_template_parameters: |
          echo music = $(meta get parameters.DOWNSTREAM_PARAM_MUSIC)
          echo movie = $(meta get parameters.DOWNSTREAM_PARAM_MOVIE)
