## Stages by grouping
shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  component:
    requires: [~pr, ~commit]
  publish:
    requires: [ component ]
  ci-deploy:
    requires: [ publish ]
  ci-test:
    requires: [ ci-deploy ]
  ci-certify:
    requires: [ ci-test ]
  prod-blue-deploy:
    requires: [ ci-certify ]
  prod-blue-test:
    requires: [ prod-blue-deploy ]
  prod-blue-certify:
    requires: [ prod-blue-test ]
  prod-green-deploy:
    requires: [ ci-certify ]
  prod-green-test:
    requires: [ prod-green-deploy ]
  prod-green-certify:
    requires: [ prod-green-test ]
